
import React, { useState, useEffect } from 'react';
import { CaseStudyProject, Dataset } from '../types';
import { generateCaseStudy } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';
import { Edit3, Eye, Sparkles, Loader2, Download } from 'lucide-react';

interface CaseStudyBuilderProps {
  dataset?: Dataset | null;
}

const CaseStudyBuilder: React.FC<CaseStudyBuilderProps> = ({ dataset }) => {
  // Default to Preview mode (false) as requested
  const [isEditing, setIsEditing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const [project, setProject] = useState<CaseStudyProject>({
    title: 'Sales Performance Analysis 2024',
    objective: '',
    dataSource: 'Internal Sales Database (CSV Export)',
    methodology: '',
    findings: '',
    conclusion: ''
  });

  const handleChange = (field: keyof CaseStudyProject, value: string) => {
    setProject(prev => ({ ...prev, [field]: value }));
  };

  const handleExportPDF = (e: React.MouseEvent) => {
    e.preventDefault();
    console.log("Triggering print dialog...");
    // Use setTimeout to ensure any pending UI renders complete and to decouple from the event
    setTimeout(() => {
        window.print();
    }, 100);
  };

  const handleAutoGenerate = async () => {
    if (!dataset) return;
    setIsGenerating(true);
    try {
        const aiResult = await generateCaseStudy(dataset);
        setProject(prev => ({
            ...prev,
            title: aiResult.title || prev.title,
            objective: aiResult.objective || prev.objective,
            methodology: aiResult.methodology || prev.methodology,
            findings: aiResult.findings || prev.findings,
            conclusion: aiResult.conclusion || prev.conclusion,
            dataSource: dataset.name
        }));
        setHasAutoGenerated(true);
        // Switch to preview mode automatically to show results
        setIsEditing(false); 
    } catch (e) {
        console.error(e);
    } finally {
        setIsGenerating(false);
    }
  };

  // Automatically generate on mount if dataset exists and hasn't generated yet
  useEffect(() => {
      if (dataset && !hasAutoGenerated) {
          handleAutoGenerate();
      }
  }, [dataset]);

  return (
    <div className="h-full flex flex-col bg-slate-50">
      {/* Toolbar */}
      <div className="bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center sticky top-0 z-10 no-print">
        <h2 className="text-lg font-bold text-slate-800">Case Study Builder</h2>
        <div className="flex space-x-2">
            {dataset && (
                <button 
                    type="button"
                    onClick={handleAutoGenerate}
                    disabled={isGenerating}
                    className="px-4 py-2 rounded-lg text-sm font-medium bg-purple-100 text-purple-700 hover:bg-purple-200 transition-colors flex items-center disabled:opacity-50"
                >
                    {isGenerating ? <Loader2 size={16} className="mr-2 animate-spin"/> : <Sparkles size={16} className="mr-2" />}
                    {isGenerating ? 'Generating...' : 'Regenerate with AI'}
                </button>
            )}
            <button 
                type="button"
                onClick={() => setIsEditing(!isEditing)}
                className="px-4 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition-colors flex items-center"
            >
                {isEditing ? <><Eye size={16} className="mr-2" /> Preview</> : <><Edit3 size={16} className="mr-2" /> Edit</>}
            </button>
            <button 
                type="button"
                onClick={handleExportPDF}
                className="px-4 py-2 rounded-lg text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 transition-colors flex items-center shadow-sm"
                title="Opens print dialog. Choose 'Save as PDF' destination."
            >
                <Download size={16} className="mr-2" />
                Export PDF
            </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto custom-scrollbar p-6">
        {/* Added 'printable-content' class here for print targeting */}
        <div className="max-w-4xl mx-auto bg-white shadow-lg rounded-xl min-h-[800px] p-12 printable-content">
            
            {/* Project Header */}
            <div className="mb-12 border-b border-slate-100 pb-8">
                {isEditing ? (
                     <div className="space-y-4">
                         <div>
                             <label className="block text-sm font-medium text-slate-500 mb-1">Project Title</label>
                             <input 
                                type="text" 
                                value={project.title}
                                onChange={(e) => handleChange('title', e.target.value)}
                                className="w-full text-4xl font-bold text-slate-900 border-0 border-b-2 border-slate-100 focus:border-blue-500 focus:ring-0 px-0 py-2 transition-colors placeholder:text-slate-300"
                                placeholder="Project Title"
                             />
                         </div>
                         <div>
                            <label className="block text-sm font-medium text-slate-500 mb-1">Data Source</label>
                            <input 
                                type="text" 
                                value={project.dataSource}
                                onChange={(e) => handleChange('dataSource', e.target.value)}
                                className="w-full text-lg text-slate-600 border-0 border-b-2 border-slate-100 focus:border-blue-500 focus:ring-0 px-0 py-2 transition-colors"
                                placeholder="Source of data"
                            />
                         </div>
                     </div>
                ) : (
                    <div className="text-center">
                        <h1 className="text-4xl font-bold text-slate-900 mb-4">{project.title}</h1>
                        <p className="text-lg text-slate-500">Data Source: {project.dataSource}</p>
                    </div>
                )}
            </div>

            {/* Sections */}
            <div className="space-y-10">
                {[
                    { id: 'objective', label: 'Project Objective', placeholder: 'Define the business problem and goals of this analysis...' },
                    { id: 'methodology', label: 'Methodology', placeholder: 'Describe tools (SQL, Python), techniques (cleaning, EDA), and models used...' },
                    { id: 'findings', label: 'Key Findings', placeholder: 'Summarize major insights using Markdown. You can paste images or charts here manually after printing, or describe trends...' },
                    { id: 'conclusion', label: 'Conclusion & Recommendations', placeholder: 'Provide actionable recommendations based on the data...' },
                ].map((section) => (
                    <section key={section.id} className="space-y-3 avoid-break">
                        <h3 className="text-xl font-bold text-slate-800 uppercase tracking-wide border-l-4 border-blue-500 pl-3">
                            {section.label}
                        </h3>
                        {isEditing ? (
                             <textarea
                                value={(project as any)[section.id]}
                                onChange={(e) => handleChange(section.id as keyof CaseStudyProject, e.target.value)}
                                placeholder={section.placeholder}
                                className="w-full min-h-[150px] p-4 rounded-lg bg-slate-50 border border-slate-200 text-slate-700 focus:ring-2 focus:ring-blue-500 outline-none resize-y"
                             />
                        ) : (
                            <div className="prose prose-slate max-w-none text-slate-700 leading-relaxed">
                                <ReactMarkdown>{(project as any)[section.id] || '*No content added.*'}</ReactMarkdown>
                            </div>
                        )}
                    </section>
                ))}
            </div>

            {!isEditing && (
                <div className="mt-16 pt-8 border-t border-slate-200 text-center text-slate-400 text-sm no-print">
                    Generated with Basic EDA Tool
                </div>
            )}

        </div>
      </div>
    </div>
  );
};

export default CaseStudyBuilder;
